### ISSUE TITLE
Server.js

### ISSUE THREAD

**Issue by Axkaban** [grolimur/web-api-course#2]
So besides the few details It looks really well, routes are great! 

On tho the meaty part 9/out of 49 is pretty great!

For the `Scoop - server.js:  /comments POST routes['/comments'].POST should create a new comment:
     AssertionError: expected undefined to equal 'Comment Body'
      at Context.<anonymous> (test/test.js:91:64)` test, you forgot to have a property `body` on your comment object in `createComment()`, the value for it is `requestComment.body`. 

for `routes['/comments'].POST should add a newly created comment's ID to the article's comment IDs` and `routes['/comments'].POST should return a 201 response containing a newly-created comment`
you need to remember that the comment is linked to an Article, so if you take a look at the readme file is not one array or articles but just one, in contrast is a relationship where each comment has only one article but one article could have many comments. You need to switch `articleIds: []` for `articleId: requestComment.articleId,` and push the comment's id to the commentIds array in Articles `database.articles[comment.articleId].commentIds.push(comment.id);`

For `routes['/comments'].POST should return a 400 response if the comment's article does not exist`
you have to check for `database.articles[requestComment.articleId]` in the if statement.

For `routes['/comments'].POST should return a 400 response if a required field is not supplied`
you have to check for the articleId, and the body from requestComment in the if statement as well.

For `routes['/comments/:id'].PUT should update an existing comment`  you did not change some of the properties to match your comment object. Comments don't have a title or url just a body:
```
 savedComment.body = requestComment.body || savedComment.body;
    console.log(savedComment);
    response.body = {comment: savedComment};
```
For `routes['/comments/:id/upvote'].PUT should return a 200 response after a succesful upvote and send back the upvoted comment` and its downvote equivalent, you need to change the property in the response, from article to comment.

and For`/comments/:id DELETE routes['/comments/:id'].DELETE should remove a deleted comment ID from the article's comment IDs:` you will also have to do a for each like in deleteArticle to get check each comment and delete the  requested one.

**Comment by grolimur** [comment]
Thanks a lot for the (very quick!) feedback.
I see better what I missed and I'll try fix those bugs to see if I understood your feedback correctly.
