### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [grolimur/web-api-course#3]
Grade: **Passing**

You met most tasks and seem to be having a main understanding of the construction of the server. It is correct that the methods were very similar(in many servers, certain things usually are alike) but you need to be careful when you copy, that certain terms translate to the specific task of the method you are working on. 

Once you've fixed the last 9 tests, give building the yaml file a try, you can use this library: [node-yaml](https://www.npmjs.com/package/node-yaml)

Best of Luck Raphaël!

**Comment by grolimur** [comment]
Thanks!
I'll do that.
